// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
     // case TargetPlatform.windows:
     //   return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWWObU38jAPgnLOlJmgrsHChgvVJqx6Wc',
    appId: '1:54159583135:web:69be211c59956c9384bfaa',
    messagingSenderId: '54159583135',
    projectId: 'vitae-3ee57',
    authDomain: 'vitae-3ee57.firebaseapp.com',
    databaseURL: 'https://vitae-3ee57-default-rtdb.firebaseio.com',
    storageBucket: 'vitae-3ee57.firebasestorage.app',
    measurementId: 'G-ESVKRFPV5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAueUb_4rmF5DgXWR9tb2dYRrbvScvDG2k',
    appId: '1:54159583135:android:dabe5f1ef957043384bfaa',
    messagingSenderId: '54159583135',
    projectId: 'vitae-3ee57',
    databaseURL: 'https://vitae-3ee57-default-rtdb.firebaseio.com',
    storageBucket: 'vitae-3ee57.firebasestorage.app',
  );


  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbIlGznuIU6QGMh7Utt77Bmzh-qwiydok',
    appId: '1:209989432554:ios:c975a46955c2b351545393',
    messagingSenderId: '209989432554',
    projectId: 'vitae-bb283',
    storageBucket: 'vitae-bb283.firebasestorage.app',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
  apiKey: 'AIzaSyAueUb_4rmF5DgXWR9tb2dYRrbvScvDG2k',
  appId: '1:54159583135:ios:4fc155fb4458b25984bfaa',
  messagingSenderId: '54159583135',
  projectId: 'vitae-3ee57',
  storageBucket: 'vitae-3ee57.firebasestorage.app',
  iosBundleId: 'com.vitaecollectivestudio.barberapp',
);
}